AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template for Multi-Region Disaster Recovery - Pilot Light (Standby Region)"

Metadata:
  Author: "Mohsin Sheikhani"

Parameters:
  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of Availability Zones to use for the subnets in the VPC.
    Default: us-east-2a,us-east-2b

  PrimaryDBIdentifier:
    Type: String
    Default: ""
    Description: The identifier of the primary DB instance for replication.

Conditions:
  CreateReadReplica: !Not [!Equals [!Ref PrimaryDBIdentifier, ""]]

Resources:
  SecondaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  RDSReadReplica1:
    Type: AWS::RDS::DBInstance
    Condition: CreateReadReplica
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      SourceDBInstanceIdentifier: !Ref PrimaryDBIdentifier
      AvailabilityZone: !Select [0, !Ref AvailabilityZones]
      Tags:
        - Key: Name
          Value: ReadReplicaInstance1

  RDSReadReplica2:
    Type: AWS::RDS::DBInstance
    Condition: CreateReadReplica
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      SourceDBInstanceIdentifier: !Ref PrimaryDBIdentifier
      AvailabilityZone: !Select [1, !Ref AvailabilityZones]
      Tags:
        - Key: Name
          Value: ReadReplicaInstance2

Outputs:
  SecondaryBucketName:
    Value: !Ref SecondaryBucket
