AWSTemplateFormatVersion: "2010-09-09"

Description: "CloudFormation template for Multi-Region Disaster Recovery - Pilot Light (Standby Region)"

Metadata:
  Author: "Mohsin Sheikhani"

Resources:
  SecondaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

Outputs:
  SecondaryBucketName:
    Value: !Ref SecondaryBucket
    Export:
      Name: SecondaryBucketName
